on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  yakamoz:
    runs-on: ubuntu-latest
    name: yakamoz
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache qmk toolchain
        uses: actions/cache@v4
        env:
          cache-name: qmk-toolchain
        with:
          path: |
            /home/runner/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies for qmk build
        uses: mstksg/get-package@v1
        with:
          apt-get: git python3-pip dfu-util dfu-programmer avrdude 
      - name: Install qmk using pip
        working-directory: ./qmk_firmware
        run: |
          python3 -m pip install --user qmk
          qmk setup --yes --home .
      - name: Prepare qmk_firmware folder
        run: cp -R yakamoz/ qmk_firmware/keyboards/

      - name: Prepare vial folder
        run: cp -R yakamoz/ vial-qmk/keyboards/

      

      - name: Build vial keymap
        working-directory: ./vial-qmk
        run: qmk compile -kb yakamoz -km vial 
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: yakamoz-keyboard-vial
          path: vial-qmk/yakamoz_vial.uf2

